# Generated by Django 4.0.4 on 2022-05-10 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('7d76f3ca-1008-4b23-bde9-5a26774ebc71'), max_length=3000),
        ),
    ]
